#!/usr/bin/env python3
"""Recover curated community labels after an external `graphify .` run overwrote them.

When someone runs the full graphify pipeline (e.g., via post-commit hook or manual
invocation), `.graphify_labels.json` is regenerated by graphify's LLM and any
human/agent curation is lost. This script reconstructs the previous labels by:

1. Reading each curated wiki file in `<vault>/raw/repos/<name>/` (these were
   generated from the *previous* graph with the previous labels — filenames
   themselves are the labels).
2. Parsing each file's "Key Concepts" section to extract top node labels.
3. Looking up where those nodes now live in the *new* `graph.json` — voting on
   community ids by frequency.
4. Greedy assignment (highest-vote labels claim their best community first),
   skipping communities already taken to avoid collisions.

Labels that fail to map (the community was merged with another, or split) are
reported on stderr so the operator can decide whether to recreate them.

Usage:
    python recover_labels.py <project-path> <vault-raw-repos-path>

Example:
    python recover_labels.py \\
        ~/workspace/foo \\
        ~/vaults/raw/repos/foo

The new `.graphify_labels.json` is written in place under the project's
graphify-out/. The previous version is backed up to `.graphify_labels.json.bak`.

Exit codes:
    0 — assignments written
    2 — bad inputs
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from collections import Counter, defaultdict
from pathlib import Path

KEY_CONCEPT_RE = re.compile(r"^- \*\*(.+?)\*\*", re.MULTILINE)
PLACEHOLDER_RE = re.compile(r"^Community \d+$")


def safe_filename(name: str) -> str:
    """Mirror graphify.wiki._safe_filename so we can map labels ↔ filenames."""
    return re.sub(r'[<>:"/\\|?*]', "-", name).replace(" ", "_")


def collect_curated_labels(repos_dir: Path) -> list[str]:
    """Find labels in raw/repos/<name>/ that are human/agent curated.

    A label is considered curated if its filename doesn't match the placeholder
    pattern. We strip the .md suffix and reverse the _safe_filename munging that
    we can (spaces ↔ underscores).
    """
    if not repos_dir.is_dir():
        return []
    curated: list[str] = []
    for md in repos_dir.glob("*.md"):
        if md.name == "index.md":
            continue
        if PLACEHOLDER_RE.match(md.stem):
            continue
        # safe_filename replaces spaces with underscores; can't perfectly reverse
        # because some labels contain real underscores. We treat the filename
        # stem as the canonical "label key" and trust that the file's H1 / body
        # carries the human-readable form for verification.
        curated.append(md.stem)
    return curated


def vote_cids(content: str, label_to_nids: dict[str, list[str]], node_to_cid: dict[str, int]) -> Counter:
    """Count community ids reached from a curated file's Key Concepts."""
    votes: Counter = Counter()
    for node_label in KEY_CONCEPT_RE.findall(content):
        for nid in label_to_nids.get(node_label, []):
            cid = node_to_cid.get(nid)
            if cid is not None:
                votes[cid] += 1
    return votes


def main(project_path: str, repos_path: str) -> int:
    project = Path(project_path).expanduser().resolve()
    repos_dir = Path(repos_path).expanduser().resolve()

    graph_path = project / "graphify-out" / "graph.json"
    labels_path = project / "graphify-out" / ".graphify_labels.json"

    if not graph_path.exists():
        print(f"error: {graph_path} not found", file=sys.stderr)
        return 2
    if not labels_path.exists():
        print(f"error: {labels_path} not found", file=sys.stderr)
        return 2
    if not repos_dir.is_dir():
        print(f"error: {repos_dir} is not a directory", file=sys.stderr)
        return 2

    graph = json.loads(graph_path.read_text())
    node_to_cid: dict[str, int] = {}
    label_to_nids: dict[str, list[str]] = defaultdict(list)
    for node in graph["nodes"]:
        cid = node.get("community")
        if cid is None:
            continue
        node_to_cid[node["id"]] = int(cid)
        lbl = node.get("label")
        if lbl:
            label_to_nids[lbl].append(node["id"])

    # Build label → (best_cid, votes) using the curated filenames
    label_votes: dict[str, Counter] = {}
    for stem in collect_curated_labels(repos_dir):
        # Look for the curated file with this stem
        candidate = repos_dir / f"{stem}.md"
        if not candidate.exists():
            continue
        votes = vote_cids(candidate.read_text(), label_to_nids, node_to_cid)
        if votes:
            # The "label" we recover is the stem with underscores → spaces. This
            # is an approximation — the operator should review final labels.json.
            recovered_label = stem.replace("_", " ")
            label_votes[recovered_label] = votes

    # Greedy assignment: labels with highest top-vote claim first
    ranked = sorted(label_votes.items(),
                    key=lambda kv: -(kv[1].most_common(1)[0][1] if kv[1] else 0))
    assigned: dict[int, str] = {}
    lost: list[tuple[str, str]] = []
    for label, votes in ranked:
        chosen = None
        for cid, vote_count in votes.most_common():
            if cid in assigned:
                continue
            if vote_count < 2:
                break  # too weak
            assigned[cid] = label
            chosen = (cid, vote_count)
            break
        if not chosen:
            top = votes.most_common(1)[0] if votes else (None, 0)
            reason = (
                f"top cid={top[0]} already taken by '{assigned.get(top[0], '?')}'"
                if top[0] in assigned else f"votes too weak (best={top[1]})"
            )
            lost.append((label, reason))

    # Merge into labels.json
    labels = json.loads(labels_path.read_text())
    shutil.copy(labels_path, str(labels_path) + ".bak")
    overwrote = 0
    for cid, label in assigned.items():
        if labels.get(str(cid)) != label:
            overwrote += 1
        labels[str(cid)] = label
    labels_path.write_text(json.dumps(labels, ensure_ascii=False, indent=2))

    print(f"recovered {len(assigned)} labels (overwrote {overwrote} entries)")
    print(f"  backup: {labels_path}.bak")
    if lost:
        print(f"  {len(lost)} labels unmappable — community structure changed:", file=sys.stderr)
        for label, reason in lost:
            print(f"    {label!r} — {reason}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__.splitlines()[0], file=sys.stderr)
        print(f"usage: {sys.argv[0]} <project-path> <vault-raw-repos-path>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
